name: app_concept_flutter
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^3.1.0+1

  flutter_localizations:
    sdk: flutter

  # Service locator
  get_it: ^2.0.1
  # Bloc for state management
  flutter_bloc: ^0.21.0
  # Value equality
  equatable: ^0.4.0
  # Functional programming thingies
  dartz: ^0.8.7
  # Remote API
  http: ^0.12.0+2
  # Local cache
  shared_preferences: ^0.5.3+4
  # Network Connection checker
  data_connection_checker: ^0.3.4

  # For String Interpolation
  sprintf: ^4.0.2


  flutter_webview_plugin: ^0.3.8
  simple_animations: ^1.3.3

  local_auth: ^0.4.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  flutter_lottie_plus: ^0.3.16

# The following section is specific to Flutter.
flutter:

  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/animations/

  fonts:
    - family: Arial
      fonts:
        - asset: assets/fonts/Arial.ttf

    - family: Avenir
      fonts:
        - asset: assets/fonts/Avenir-Black.ttf
        - asset: assets/fonts/Avenir-BlackOblique.ttf
        - asset: assets/fonts/Avenir-Book.ttf
        - asset: assets/fonts/Avenir-BookOblique.ttf
        - asset: assets/fonts/Avenir-Heavy.ttf
        - asset: assets/fonts/Avenir-HeavyOblique.ttf
        - asset: assets/fonts/Avenir-Light.ttf
        - asset: assets/fonts/Avenir-LightOblique.ttf
        - asset: assets/fonts/Avenir-Medium.ttf
        - asset: assets/fonts/Avenir-MediumOblique.ttf
        - asset: assets/fonts/Avenir-Oblique.ttf
        - asset: assets/fonts/Avenir-Roman.ttf
          weight: 700

    - family: GlyphaLTStd
      fonts:
        - asset: assets/fonts/GlyphaLTStd-Black.otf
        - asset: assets/fonts/GlyphaLTStd-BlackOblique.otf
        - asset: assets/fonts/GlyphaLTStd-Bold.otf
          weight: 700
        - asset: assets/fonts/GlyphaLTStd-BoldOblique.otf
          weight: 700
        - asset: assets/fonts/GlyphaLTStd-Light.otf
        - asset: assets/fonts/GlyphaLTStd-LightOblique.otf
        - asset: assets/fonts/GlyphaLTStd-Oblique.otf
        - asset: assets/fonts/GlyphaLTStd-Thin.otf
        - asset: assets/fonts/GlyphaLTStd-ThinOblique.otf